scikit-hep/uproot-browser

pyproject.toml

This should upload an SDist now after https://github.com/takluyver/flit/issues/422 was fixed in 3.3.
If this works (and I expect it to), then I'll update scikit-hep/cookie.

fix: dist upload

---

src/uproot_browser/__main__.py

Enables usage of `-h` in addition to `--help` for calling the help page.
```
$ uproot-browser -h
Usage: uproot-browser [OPTIONS] COMMAND [ARGS]...
Must provide a subcommand.
Options:
-h, --help  Show this message and exit.
Commands:
plot  Display a plot.
tree  Display a tree.
```

feat: add -h to default parameters

---

src/uproot_browser/__main__.py

In reference to #12 
Should we rename `tui.py` and corresponding calls too, @henryiii? Looks good to me as it is though.

chore: rename tui to browse

---

pyproject.toml
src/uproot_browser/plot_view.py

- Add basic error handling which fixes crashes with help from @henryiii
- Use a workaround for traceback height till it's fixed in Textualize/rich#2042

feat: add error handling to prevent crash

---

src/uproot_browser/__main__.py

Ugly workaround for https://github.com/daleroberts/itermplot/issues/35.

fix: hack around color problem in itermplot

---

README.md
pyproject.toml
src/uproot_browser/__init__.py
tests/test_package.py

Dropping `__version__`; while I'm in the "it's nice to have" camp, maintaining a version in pyproject.toml is easier (I'll assume it's automatic otherwise), and it's not worth the bother to add `importlib_metadata` to make this work the other direction. This is not a library, so no one should be importing it anyway.
Added pre-commit.ci, and a placeholder badge for https://github.com/conda-forge/staged-recipes/pull/18382.

chore: bump to version 0.4.0

---

pyproject.toml

- Update minimum required to uproot version to `4.2.1` due to the change in `fBits` size definition
- Refer to [4d0ef10](https://github.com/amangoel185/uproot-browser/commit/4d0ef10fef4ea9e6dd4f46c3179452a9c7d06774) and scikit-hep/uproot4/pull/570

chore: update minimum required uproot version

---

.github/dependabot.yml

Remove obsolete configuration from `dependabot.yml` similar to scikit-hep/hist#420

chore: cleanup dependabot.yml

---

src/uproot_browser/tree.py

Resolves #47
* Determine if the read only directory path is the top of the tree (and so an empty tuple) or if it is a path inside of the file. From this link the directory (file) path to the directory (file) name.
```
uproot-browser tree /tmp/FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
```
📁 FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
┣━━ 📁 FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
┃   ┗━━ 🌴 Events (40600)
┃       ┣━━ 🍃 electron_ch std::vector<float>
┃       ┣━━ 🍃 electron_dxy std::vector<float>
┃       ┣━━ 🍃 electron_dxyError std::vector<float>
┃       ┣━━ 🍃 electron_dz std::vector<float>
┃       ┣━━ 🍃 electron_dzError std::vector<float>
┃       ┣━━ 🍃 electron_e std::vector<float>
┃       ┣━━ 🍃 electron_eta std::vector<float>
┃       ┣━━ 🍃 electron_isLoose std::vector<bool>
┃       ┣━━ 🍃 …

fix: Link directory paths to directory names

---

pyproject.toml
src/uproot_browser/plot.py

1-D Histograms were zero suppressed, causing improper display of plots.

feat: set lower y limit to zero

---

src/uproot_browser/exceptions.py
src/uproot_browser/plot.py
src/uproot_browser/plot_view.py

Resolves #53.
In the event that a branch is empty, instead of catching the `Exception` and displaying the frames in the panel, raise a `ValueError` and catch that to display in the panel that the branch is 'EMPTY'.
```
uproot-browser browse /tmp/data_A.2lep.root
```
When opening a branch that is empty get a traceback from the caught exception.
```
uproot-browser browse /tmp/data_A.2lep.root
```
When opening a branch that is empty get text of "{branch name} is EMPTY" (e.g. "largeRjet_D2 is EMPTY").

fix: Note branch empty on panel instead of traceback

---

pyproject.toml

Just Added "itermplot==0.5" to the pyproject.toml, correct me if that wasn't the right place to change this.

itermplot version correction

---

src/uproot_browser/tui/browser.css
src/uproot_browser/tui/browser.py
src/uproot_browser/tui/left_panel.py

Fixing browser colors to be closer to Textual's default

fix: browser colors

---

src/uproot_browser/tui/browser.py
src/uproot_browser/tui/header.py

We went back to the default header, but someone noticed it was missing. This restores the x.  Closes #124. A ❓ could be added on the other side after #130. :)

fix: restore the x in the header

---

src/uproot_browser/tui/browser.py

By moving the reactive `.dark` setting, we get a single refresh instead of two.

fix: plot and theme toggle at the same time

---

src/uproot_browser/plot.py

Plotext has a sane default of displaying five regularly-spaced ticks on the x-axis when using `plt.hist`. However, since uproot-browser uses `hist.Hist` to do the histogramming (and for good reason), Plotext changes to insane plot ticks for some reason - irregularly spaced ticks with long mantissas. This PR restores the default `plt.hist` behavior of showing five regularly-spaced ticks.

Change x-axis to 5 regularly-spaced ticks

---

src/uproot_browser/tui/README.md

Small typos fixed, and a little note about plots.

docs: fix some typos in the help

---

.pre-commit-config.yaml
src/uproot_browser/tui/left_panel.py

"h" and "j" keys were broken.
Once we bump the minimum Textual (which might be soon due to the new overlay system!), then this extra workaround can be dropped.

fix: support Textual 0.24

---

.gitignore
noxfile.py
src/uproot_browser/tui/browser.css

Fix #164 which was broken by https://github.com/Textualize/textual/pull/3059.
This seems to be the only breakage at least till 0.64 (current).

fix: support textual 0.33+

---

.github/workflows/cd.yml
.github/workflows/ci.yml
pyproject.toml

ci: 3.13 and some touchup

---

src/uproot_browser/plot.py

More info when something fails to plot (including if you dump with "d" so you can copy-paste it, etc).

fix: show the type that failed to plot

---

src/uproot_browser/tree.py

Using single dispatch a bit more. Should make #195 nicer.

refactor: more singledispatch

---

src/uproot_browser/tui/browser.py
tests/test_tui.py

Fix the bug of having the same theme for the plot area after switching it.

Fix theme switching for the plot widget

---

noxfile.py
pyproject.toml
src/uproot_browser/tui/README.md
src/uproot_browser/tui/browser.css
src/uproot_browser/tui/browser.py
src/uproot_browser/tui/help.py
src/uproot_browser/tui/tools.py
tests/test_tui.py

Inspired by the work of @eeelie in https://github.com/scikit-hep/uproot-browser/tree/feat/right-panel, but applying the idea to the left panel and adding tabs instead. Just some basic things here now, but hopefully this can become content aware and allow controls over the plot / data.
- **chore: use yield for content switcher**
- **fix: esc will also quit**
- **feat: add tabs for the left panel**
Stuck on a bug for a bit that was already fixed in https://github.com/scikit-hep/uproot-browser/pull/198

feat: tabbed left panel

---

src/uproot_browser/tui/tools.py

fix: empty theme shouldn't be possible

---

src/uproot_browser/plot.py
src/uproot_browser/tui/browser.py
src/uproot_browser/tui/messages.py
src/uproot_browser/tui/plot.py
tests/test_tui.py

The slowest thing right now is actually the error rendering, and this is a little messy. Maybe it can be cleaned up and applied to errors too.

fix: faster (threaded) plotting
