- .pre-commit-config.yaml
- docs/conf.py
- noxfile.py
- pyproject.toml
- src/uproot_browser/__init__.py
- src/uproot_browser/__main__.py
- src/uproot_browser/dirs.py
- src/uproot_browser/plot.py
- tests/test_dirs.py
- tests/test_package.py
Basic plotting support.
- feat: add plotting feature
- fix: working plot
> feat: plot

- src/uproot_browser/plot.py
Plotting support for histograms.
Examples:
```
$ uproot-browser plot ../scikit-hep-testdata/src/skhep_testdata/data/uproot-Event.root:htime
$ uproot-browser plot ../scikit-hep-testdata/src/skhep_testdata/data/uproot-Event.root:hstat
```
> feat: add plot function for histograms

- README.md
> docs: add basic information to README.md

- .pre-commit-config.yaml
- src/uproot_browser/__main__.py
- src/uproot_browser/plot_view.py
- src/uproot_browser/tree.py
- src/uproot_browser/tree_view.py
- src/uproot_browser/tui.py
This runs something (not very much - no contents, no interaction, no plot, but something) in a TUI. Hopefully a better starting point! I'm targeting our WIP branch, so feel free to merge unless it clashes with what you are doing.
I've mostly restructured the way trees work so that there's a (poorly named as Node) class, and that simplifies the dual usage (from TUI and tree).
> feat: empty TUI

- src/uproot_browser/plot_view.py
Adding a small logo.
Similar changes should be done to place a nice error message / traceback into this area - the only difference will be it might need to be scrollable.
> feat: add a little logo

- src/uproot_browser/plot.py
- src/uproot_browser/plot_view.py
> feat: add better plot information

- src/uproot_browser/plot_view.py
Removing some unneeded things. Moved the logo to avoid dedent. Adding textual to the "powered by". Also added Scikit-HEP - hopefully this will be in Scikit-HEP soon, but even now, it's being powered by Scikit-HEP libraries (uproot, awkward, hist), so I think that's okay.
> chore: clean up unused bits

- .pre-commit-config.yaml
- noxfile.py
- pyproject.toml
- src/uproot_browser/__main__.py
- src/uproot_browser/plot.py
- src/uproot_browser/plot_mpl.py
- src/uproot_browser/plot_view.py
This is not quite ideal until we fix Hist's desire to import SciPy for all plots.
> feat: iterm mode for plot

- src/uproot_browser/header.py
- src/uproot_browser/tui.py
In reference to #12
- Add filename as the subtitle
- Change 🐞 to 📊
- Have made some changes compared to the [original](https://github.com/Textualize/textual/blob/main/src/textual/widgets/_header.py) - removing unused imports etc.
- Also removed `event: events.Mount` from `on_mount`
> feat: reimplement header with modifications

- src/uproot_browser/header.py
> fix: minor cleanup after merge

- src/uproot_browser/header.py
@amangoel185 feel free to add to this PR to polish and find some styles/icons that look good. But it does generally seem to work.
> WIP: try close and hover style for X

- src/uproot_browser/tree_view.py
> feat: add basic hover styling

- .pre-commit-config.yaml
- src/uproot_browser/tree.py
Fixing #25.
We need to come up with tests. We can use scikit-hep-testdata, and compare the output of tree and plot with expectation.
> fix: Python 3.7/8 support restored

- .github/workflows/ci.yml
- pyproject.toml
- src/uproot_browser/tree.py
- tests/test_printouts.py
> tests: adding a test for tree view

- src/uproot_browser/__main__.py
- src/uproot_browser/dirs.py
- src/uproot_browser/plot_view.py
- src/uproot_browser/tui.py
> feat: dump to terminal on quit

- src/uproot_browser/plot.py
Other half of https://github.com/scikit-hep/hist/issues/393
> fix: non finite values removed

- .pre-commit-config.yaml
- chore: use new click
https://github.com/pallets/click/pull/2233
We are also skipping around the typer bug affecting pycln using the newly released typer. ;)
> chore: click

- README.md
Add the license badge to `README.md` similar to scikit-hep/hist#417
> docs: add the license badge

- .github/CONTRIBUTING.md
- pyproject.toml
> chore: hatchling

- src/uproot_browser/__main__.py
Add `--logging` flag as suggested by @matthewfeickert in #55
> feat: add flag for logging

- .github/workflows/ci.yml
- pyproject.toml
> chore: add Python 3.11 testing

- pyproject.toml
Tested, too many changes to work with 0.2 (CSS branch) coming out next week (on 10/24, or 1KB day).
> chore: limit textual to 0.1.x only

- .github/CONTRIBUTING.md
Add `nox -l` and remove extra whitespace
> docs: update CONTRIBUTING.md and fix whitespace

- README.md
> docs: add --version information to README.md

- README.md
Change to 'text user interface'
> docs: fix TUI full form

- pyproject.toml
- src/uproot_browser/tree.py
> fix: duplicate directory listing

- src/uproot_browser/tree.py
- tests/test_printouts.py
- fix: tree structure no longer flattened
> fix: tree structure no longer flattened

- src/uproot_browser/tui/browser.css
- src/uproot_browser/tui/browser.py
- src/uproot_browser/tui/left_panel.py
- Fixed tree to highlight selected item
> fix: highlight selection

- pyproject.toml
- src/uproot_browser/tree.py
- src/uproot_browser/tui/browser.css
- src/uproot_browser/tui/browser.py
- src/uproot_browser/tui/left_panel.py
Fixing up labels so we can detect the two parts.
> fix: split up meta for label

- .pre-commit-config.yaml
- pyproject.toml
- src/uproot_browser/tui/browser.py
- updated minimum textual version to 0.18.0
- changed plotext background light theme color to match textual theme
> fix: updated minimum textual version

- README.md
> dox: update gif

- src/uproot_browser/tui/left_panel.py
Closes #125. Adds `hjkl`. Search is a separate, harder to implement feature. ;)
> feat: add vim-like navigation

- pyproject.toml
- src/uproot_browser/_compat/importlib/resources.py
- src/uproot_browser/_compat/typing.py
- src/uproot_browser/tree.py
- src/uproot_browser/tui/README.md
- src/uproot_browser/tui/browser.css
- src/uproot_browser/tui/browser.py
- src/uproot_browser/tui/header.py
- src/uproot_browser/tui/help.py
- src/uproot_browser/tui/left_panel.py
Closes #128. (Edit: forgot to bump the textual version for this. Also we might want to work out the flicker issue introduced in... 0.19, I think? Or was it 0.20... ~~first~~, since we probably can't toggle between those versions anymore after this is added.
Nevermind, actually, we can just test the issue on 0.5.0. :)
> feat: add a help screen

- src/uproot_browser/tui/browser.css
> Centered EmptyWidget text

- pyproject.toml
- tests/test_tui.py
Following the method textual uses to test itself.
> tests: add basic tui tests

- src/uproot_browser/tui/help.py
- tests/test_tui.py
> fix: focus correctly when loading help screen

- .github/workflows/ci.yml
- noxfile.py
- pyproject.toml
- tests/constraints.txt
Check minimum versions of dependencies.
> tests: test minimum versions

- .github/workflows/ci.yml
- pyproject.toml
> ci: update

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
> chore: udpate ruff config and format

- pyproject.toml
- src/uproot_browser/__main__.py
Fixes regression in https://github.com/scikit-hep/uproot-browser/pull/158.
> fix: arguments can take a colon

- .github/CONTRIBUTING.md
- .pre-commit-config.yaml
- noxfile.py
- pyproject.toml
- src/uproot_browser/tui/browser.css
- src/uproot_browser/tui/browser.py
- tests/test_tui.py
Big theming changes in 0.86. Looks a little weird on .86, but good enough for now. We can require a higher version soon.
Fix #184
> fix: support textual 0.86 to 1.0.0

- .github/workflows/ci.yml
> ci: fix auto-cancel

- src/uproot_browser/tui/browser.py
Some fixes related to light/dark plots.
> fix: better dark plot matching

- src/uproot_browser/tui/header.py
- src/uproot_browser/tui/left_panel.py
- Allow to use keyboard for header buttons
> fix: add keyboard controls for header

- .pre-commit-config.yaml
- README.md
- pyproject.toml
- src/uproot_browser/__main__.py
Adding a `--testdata` flag to make it easier to run demos.
By the way, `skhep_testdata.data_path` is case sensitive on a non-case sensitive filesystem.
> feat: add --testdata

- pyproject.toml
- src/uproot_browser/plot.py
- src/uproot_browser/tui/browser.css
- src/uproot_browser/tui/browser.py
- src/uproot_browser/tui/plot.py
- src/uproot_browser/tui/tools.py
- src/uproot_browser/tui/viewer.py
Close #143. Adds an experimental entry box, enabled in tools.
> feat: entry box
